name: PR debug 2

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - cicd

jobs:
  build_tests:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64", "arm64"]
    uses: ./.github/workflows/sub_building.yml
    with:
      DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
      IMAGE_BASE_NAME: ${{ inputs.IMAGE_BASE_NAME }}
      IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
      DOCKERFILE: ${{ inputs.DOCKERFILE }}
      ARCH: ${{ matrix.arch }}
      PR_MODE: true
