name: (level 1 sub) Code compliance

on: workflow_call

jobs:
  code-check:
    name: Function check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checked_function: [ "colorecho", "add-aliases", "add-history", "add-test-command", "add-to-list" ]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Check ${{ matrix.checked_function }}
      run: python3 sources/code_compliance_check.py ${{ matrix.checked_function }}
  temp-fix:
    name: Temp-fix check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Check temp-fix
      run: python3 sources/code_compliance_check.py temp-fix
  shellcheck:
    name: Shell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1071 -e SC2148 -e SC1090 -e SC1091 -e SC2317
        with:
          ignore_names: >-
            zshrc
            bashrc